(() => {
  const $ = (s) => document.querySelector(s);
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>'\"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '\"': '&quot;' }[char]));
  let supabase = null;
  let mode = 'login';
  let busy = false;

  function injectStyles() {
    if ($('#authStyles')) return;
    const style = document.createElement('style');
    style.id = 'authStyles';
    style.textContent = `
      .auth-modal-backdrop{position:fixed;inset:0;z-index:9999;background:rgba(17,24,12,.42);backdrop-filter:blur(8px);display:none;align-items:center;justify-content:center;padding:20px}.auth-modal-backdrop.open{display:flex}
      .auth-modal{width:min(440px,100%);background:#fff;border:1px solid #e3e9dc;border-radius:24px;box-shadow:0 28px 80px rgba(20,30,15,.22);padding:28px;position:relative}.auth-close{position:absolute;right:16px;top:16px;width:38px;height:38px;border:0;border-radius:50%;background:#f4f6f0;cursor:pointer;font-size:20px}.auth-brand{display:flex;align-items:center;gap:10px;font-weight:800;font-size:20px;color:#20251b;margin-bottom:18px}.auth-brand-mark{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:#dff3a4;color:#25300f;font-weight:900}.auth-modal h2{margin:0 0 7px;font:700 28px/1.15 'Space Grotesk',sans-serif;color:#20251b}.auth-modal p{color:#68705e;margin:0 0 20px;line-height:1.5}.auth-field{margin:13px 0}.auth-field label{display:block;font-size:13px;font-weight:700;margin-bottom:7px;color:#3e4635}.auth-field input{width:100%;box-sizing:border-box;border:1px solid #d9dfd2;border-radius:12px;padding:13px 14px;font:inherit;outline:none;background:#fbfcfa}.auth-field input:focus{border-color:#9abb4b;box-shadow:0 0 0 3px rgba(168,216,62,.16)}.auth-submit{width:100%;border:0;border-radius:13px;padding:13px 16px;background:#25300f;color:#fff;font-weight:800;cursor:pointer;margin-top:8px}.auth-submit:disabled{opacity:.6;cursor:wait}.auth-switch{margin-top:16px;text-align:center;font-size:13px}.auth-switch button,.auth-forgot{border:0;background:none;color:#536b18;font-weight:800;cursor:pointer}.auth-forgot{display:block;margin:12px auto 0;font-size:13px}.auth-message{min-height:20px;margin:12px 0 0!important;font-size:13px!important}.auth-message.error{color:#a23a32}.auth-message.success{color:#477019}.auth-user-menu{position:fixed;z-index:9998;right:28px;top:72px;width:240px;background:#fff;border:1px solid #e0e6d8;border-radius:16px;box-shadow:0 18px 45px rgba(20,30,15,.16);padding:8px;display:none}.auth-user-menu.open{display:block}.auth-user-email{padding:11px 12px;font-size:12px;color:#68705e;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.auth-menu-btn{width:100%;text-align:left;border:0;background:transparent;border-radius:10px;padding:11px 12px;cursor:pointer;font-weight:700}.auth-menu-btn:hover{background:#f3f6ee}@media(max-width:600px){.auth-modal{padding:23px;border-radius:20px}.auth-user-menu{right:14px;top:66px}}
    `;
    document.head.appendChild(style);
  }

  function injectMarkup() {
    if ($('#authBackdrop')) return;
    const wrap = document.createElement('div');
    wrap.innerHTML = `<div class="auth-modal-backdrop" id="authBackdrop" role="dialog" aria-modal="true" aria-labelledby="authTitle"><div class="auth-modal"><button class="auth-close" id="authClose" aria-label="Close login">×</button><div class="auth-brand"><span class="auth-brand-mark">₹</span><span>Price Compare</span></div><h2 id="authTitle">Welcome back</h2><p id="authSubtitle">Sign in to save wishlists, alerts and searches.</p><form id="authForm"><div class="auth-field"><label for="authEmail">Email</label><input id="authEmail" type="email" autocomplete="email" required placeholder="you@example.com"></div><div class="auth-field"><label for="authPassword">Password</label><input id="authPassword" type="password" minlength="6" autocomplete="current-password" required placeholder="At least 6 characters"></div><div class="auth-field" id="authNameField" style="display:none"><label for="authName">Name</label><input id="authName" type="text" autocomplete="name" placeholder="Your name"></div><button class="auth-submit" id="authSubmit" type="submit">Sign in</button><p class="auth-message" id="authMessage" role="status"></p></form><button class="auth-forgot" id="authForgot" type="button">Forgot password?</button><div class="auth-switch"><span id="authSwitchText">Don't have an account?</span> <button id="authSwitch" type="button">Create account</button></div></div></div><div class="auth-user-menu" id="authUserMenu"><div class="auth-user-email" id="authUserEmail"></div><button class="auth-menu-btn" id="authProfileBtn">👤 Account</button><button class="auth-menu-btn" id="authLogoutBtn">↪ Sign out</button></div>`;
    document.body.appendChild(wrap);
  }

  function setMessage(text, type = '') { const el = $('#authMessage'); if (!el) return; el.textContent = text; el.className = `auth-message ${type}`; }
  function setMode(next) { mode = next; const signup = mode === 'signup'; $('#authTitle').textContent = signup ? 'Create your account' : 'Welcome back'; $('#authSubtitle').textContent = signup ? 'Create an account to keep your prices, wishlists and alerts synced.' : 'Sign in to save wishlists, alerts and searches.'; $('#authSubmit').textContent = signup ? 'Create account' : 'Sign in'; $('#authNameField').style.display = signup ? 'block' : 'none'; $('#authForgot').style.display = signup ? 'none' : 'block'; $('#authSwitchText').textContent = signup ? 'Already have an account?' : "Don't have an account?"; $('#authSwitch').textContent = signup ? 'Sign in' : 'Create account'; setMessage(''); }
  function openAuth(nextMode = 'login') { setMode(nextMode); $('#authBackdrop').classList.add('open'); setTimeout(() => $('#authEmail').focus(), 30); }
  function closeAuth() { $('#authBackdrop').classList.remove('open'); setMessage(''); }

  function updateProfileButton(user) { const btn = $('.profile-button'); if (!btn) return; if (!user) { btn.innerHTML = '<span>Login</span>'; btn.title = 'Sign in'; return; } const name = user.user_metadata?.full_name || user.user_metadata?.name || user.email?.split('@')[0] || 'User'; const initials = name.split(/\s+/).map((x) => x[0]).join('').slice(0,2).toUpperCase(); btn.innerHTML = `<span>${escapeHtml(initials)}</span><i class="icon-chevron-down"></i>`; btn.title = name; $('#authUserEmail').textContent = user.email || name; }

  async function loadSupabase() { try { const response = await fetch('/api/auth-config', { headers: { Accept: 'application/json' } }); const config = await response.json(); if (!config.configured) return false; const mod = await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'); supabase = mod.createClient(config.url, config.key, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }); const { data } = await supabase.auth.getSession(); updateProfileButton(data.session?.user || null); supabase.auth.onAuthStateChange((_event, session) => updateProfileButton(session?.user || null)); return true; } catch (error) { console.error('Auth initialization error:', error); return false; } }

  async function submitAuth(event) { event.preventDefault(); if (busy || !supabase) return; busy = true; const submit = $('#authSubmit'); submit.disabled = true; setMessage(mode === 'signup' ? 'Creating your account…' : 'Signing in…'); const email = $('#authEmail').value.trim(); const password = $('#authPassword').value; try { if (mode === 'signup') { const name = $('#authName').value.trim(); const result = await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }); if (result.error) throw result.error; if (!result.data.session) setMessage('Account created. Check your email to confirm your account.', 'success'); else { setMessage('Account created successfully.', 'success'); setTimeout(closeAuth, 700); } } else { const result = await supabase.auth.signInWithPassword({ email, password }); if (result.error) throw result.error; setMessage('Signed in successfully.', 'success'); setTimeout(closeAuth, 500); } } catch (error) { setMessage(error?.message || 'Authentication failed. Please try again.', 'error'); } finally { busy = false; submit.disabled = false; } }

  async function forgotPassword() { if (!supabase) return setMessage('Login service is not configured yet.', 'error'); const email = $('#authEmail').value.trim(); if (!email) return setMessage('Enter your email first.', 'error'); try { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: window.location.origin }); if (error) throw error; setMessage('Password reset email sent. Check your inbox.', 'success'); } catch (error) { setMessage(error?.message || 'Unable to send reset email.', 'error'); } }

  async function boot() { injectStyles(); injectMarkup(); const profile = $('.profile-button'); if (profile) profile.addEventListener('click', () => { if (!supabase) { openAuth('login'); setMessage('Login is ready, but Supabase is not configured on Vercel yet.', 'error'); return; } const hasUser = $('#authUserEmail').textContent.trim(); if (hasUser) $('#authUserMenu').classList.toggle('open'); else openAuth('login'); }); $('#authClose').addEventListener('click', closeAuth); $('#authBackdrop').addEventListener('click', (e) => { if (e.target.id === 'authBackdrop') closeAuth(); }); $('#authSwitch').addEventListener('click', () => setMode(mode === 'login' ? 'signup' : 'login')); $('#authForm').addEventListener('submit', submitAuth); $('#authForgot').addEventListener('click', forgotPassword); $('#authLogoutBtn').addEventListener('click', async () => { if (supabase) await supabase.auth.signOut(); $('#authUserMenu').classList.remove('open'); updateProfileButton(null); if (typeof showToast === 'function') showToast('Signed out successfully'); }); document.addEventListener('click', (e) => { if (!e.target.closest('.profile-button') && !e.target.closest('#authUserMenu')) $('#authUserMenu').classList.remove('open'); }); const configured = await loadSupabase(); if (!configured) updateProfileButton(null); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();
